import type { RuntimeConfig } from "./types";

export const DEFAULT_RUNTIME_CONFIG: RuntimeConfig = {
  scanner: {
    binanceBaseUrl: "https://fapi.binance.com",
    scanIntervalMs: 30_000,
    minVolume24h: 50_000_000,
    minRvol: 1.3,
    topListSize: 20,
    analysisListSize: 10,
    symbolCooldownMs: 300,
    watchlistCheckCooldownMs: 200,
    excludedSymbolPrefixes: ["BTC", "1000"],
    quoteAsset: "USDT",
    candles15mLimit: 100,
    candles5mLimit: 60,
    candlesH1Limit: 50,
    minCandles15m: 60,
    volumeLookback: 20,
    snapshotRvolFallback: 1.5,
    signalTtlMs: 4 * 60 * 60 * 1000,
    watchlistTtlMs: 2 * 60 * 60 * 1000,
    snapshotFreshnessWindowMs: 5 * 60 * 1000,
    minScoreTrade: 80,
    minScoreWatchlist: 80,
    maxOpenTrades: 3,
    maxDailyTrades: 5,
    maxWeeklyTrades: 15,
  },
  signal: {
    emaFastPeriod: 20,
    emaSlowPeriod: 50,
    emaTrendPeriod: 100,
    atrPeriod: 14,
    rvolLookback: 20,
    minCandles15m: 60,
    structureLookback: 8,
    breakoutLookback: 10,
    retestTolerance: 0.003,
    setupRetestTolerance: 0.004,
    fakeoutWickRatio: 0.5,
    fakeoutVolumeRatio: 0.7,
    candleBodyRatio: 0.4,
    momentumCandles: 3,
    mtfMinCandles: 20,
    minTimeframeAlignment: 2,
    timeframeScoreMultiplier: 2,
    minAnalysisScore: 80,
    maxScore: 100,
    volumeExpansionRvol: 2.5,
    emaPullbackTolerance: 0.005,
    supportResistanceTolerance: 0.01,
    supportResistanceLookback: 20,
    supportResistanceBaseLookback: 10,
    swingLookback: 15,
    atrSwingBuffer: 0.3,
    atrEmaBuffer: 1.2,
    atrMaxStopBuffer: 2.5,
    maxRiskPercent: 0.06,
    tp1RiskMultiple: 1.5,
    tp2RiskMultiple: 2.5,
    tp3RiskMultiple: 4,
    minRrRatio: 2,
    gradeAPlusScore: 95,
    confidenceExtremeScore: 97,
    confidenceVeryHighScore: 93,
    confidenceHighScore: 90,
    confidenceMediumScore: 85,
    volumeScoreVeryHigh: 500_000_000,
    volumeScoreHigh: 200_000_000,
    volumeScoreMedium: 100_000_000,
    volumeScoreMin: 50_000_000,
    rvolScoreExtreme: 3.0,
    rvolScoreVeryHigh: 2.5,
    rvolScoreHigh: 2.0,
    rvolScoreMediumHigh: 1.8,
    rvolScoreMin: 1.5,
  },
  risk: {
    riskPercent: 1,
    cooldownMinutes: 15,
    maxConsecutiveLosses: 2,
    pauseAfterLossesMinutes: 60,
    dailyDrawdownLimitPercent: 3.0,
    maxDrawdownPercent: 100,
    emergencyPauseMinutes: 24 * 60,
    manualPauseDefaultMinutes: 60,
    recentLossLookback: 5,
    maxExposurePercent: 100,
    maxPortfolioRiskPercent: 100,
    maxAccountRiskPercent: 100,
    maxSectorExposurePercent: 100,
    maxCoinExposurePercent: 100,
    killSwitch: false,
  },
  paperTrading: {
    defaultEquity: 10_000,
    defaultLeverage: 1,
    fixedTradeNotional: 100,
    tradingFeeRate: 0,
    makerFeeRate: 0,
    takerFeeRate: 0,
    commissionRate: 0,
    slippageRate: 0,
    fundingRate: 0,
    fundingIntervalHours: 8,
    defaultQuantity: 1,
    breakEvenPnlThreshold: 0.001,
  },
  priceTracker: {
    binanceBaseUrl: "https://fapi.binance.com",
    pollIntervalMs: 3_000,
    symbolRefreshMs: 30_000,
    fetchTimeoutMs: 4_000,
  },
  slMonitor: {
    checkIntervalMs: 30_000,
  },
  scannerDecision: {
    technicalWeight: 40,
    marketRegimeWeight: 15,
    liquidityWeight: 10,
    volumeWeight: 10,
    trendWeight: 10,
    volatilityWeight: 5,
    sessionWeight: 5,
    riskRewardWeight: 5,
    minConfidence: 0,
    minLiquidityScore: 0,
    minSessionQuality: 0,
    minVolatilityScore: 0,
    maxVolatilityScore: 100,
    maxRiskGrade: "EXTREME",
    gradeAPlusThreshold: 95,
    gradeAThreshold: 90,
    gradeBThreshold: 80,
    strategyTrendingBull: "Breakout / Pullback",
    strategyTrendingBear: "Breakdown / Pullback",
    strategySideways: "Mean Reversion",
    strategyVolatile: "Momentum only",
    strategyCompression: "Breakout Preparation",
    strategyExpansion: "Trend Continuation",
  },
  ai: {
    enabled: false,
    modelName: "gemini-2.5-flash",
    temperature: 0.2,
    maxTokens: 2048,
    timeoutMs: 20000,
    retryCount: 2,
    retryDelayMs: 750,
    cacheTtlMs: 600000,
    rateLimitPerMinute: 15,
  },
  notifications: {
    telegramEnabled: true,
  },
};
